spring.application.name=training-app-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/training_app
spring.datasource.username=training_app
spring.datasource.password=training_app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


logging.level.org.springframework.security=INFO
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration